{"errorMessage": "Failed to load TensorFlow model: Could not locate function 'mae'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'module': 'keras.metrics', 'class_name': 'function', 'config': 'mae', 'registered_name': 'mae'}", "errorType": "RuntimeError", "requestId": "0c507cee-d674-4b4d-b2da-7701d6608a35", "stackTrace": ["  File \"/var/task/app.py\", line 57, in handler\n    load_tf_model() # Ensure model is loaded\n", "  File \"/var/task/app.py\", line 50, in load_tf_model\n    raise RuntimeError(f\"Failed to load TensorFlow model: {e}\")\n"]}